### PR TITLE
Prefix PHP vendor dependencies

### LINKED ISSUE #266: Namespace conflicts with Simply Static Pro plugin.
They bundle the AlgoliaSearch PHP client with their plugin as well.

https://patrickposner.dev/plugins/simply-static/

https://wordpress.org/support/topic/namespace-conflict-with-other-plugin/

### PR DESCRIPTION
**Pull request by richaber**
Closes #266

This PR would implement the [brianhenryie/strauss](https://github.com/BrianHenryIE/strauss) package, to prefix PHP vendor dependencies, so that we may avoid namespace collisions such as reported in #266. For example, the Algolia PHP Client's `Algolia\AlgoliaSearch` namespace would become `WebDevStudios\WPSWA\Algolia\AlgoliaSearch` in the shipped version of WPSWA. I configured it so that Strauss would run on Composer's `post-install-cmd` and `post-update-cmd` events.

Things to note...
I have removed the `includes/libraries/algoliasearch-client-php/` directory.
I have configured Strauss to copy the prefixed vendor libs into a `vendor_prefixed` directory.
I have gitignored the `vendor_prefixed` directory.
I would expect a build process to include the prefixed libs in the WPORG release of the plugin.
I have deprecated the `algolia_should_require_search_client` filter, as it would no longer be necessary with a prefixed Algolia PHP Client.
I bumped the plugin `PATCH` version to `2.3.2`, as this is a bugfix for #266. However, one _could_ argue that this is a `MAJOR` version change. For example, if someone wrote some code of their own that depended on our inclusion of the Algolia PHP Client, and their code expected the `Algolia\AlgoliaSearch` namespace, rather than our prefixed namespace. Though I would argue that they should then include their own copy of the Algolia PHP Client. I do not have a strong opinion on the versioning, and leave it in your hands to decide.

I have tested against a fresh WP install, on Local, using PHP `7.3.5`, as I no longer have access to PHP `7.2`. Testing looks good for me, but I would advise that you give it a test as well.

Passes linting...
```
17:02 $ composer run lint
> @php ./vendor/squizlabs/php_codesniffer/bin/phpcs --standard=phpcs.xml --extensions=php .
.......................................... 42 / 42 (100%)


Time: 491ms; Memory: 16MB
```

### CODE REVIEW

**Comment by tw2113** [comment]
I definitely think this should be at minimum a 2.4.0 version bump. I don't think it's going to be devastating to most people like #232 will be.

Other than that, as I was reading through the code changes I was formulating thoughts and questions, and then I fully read your PR comment an basically had all of them answered. Like Richard do.

**Comment by tw2113** [comment]
Things are working on my end for testing. no issues indexing, and with a client project, we're using some code from the utils class but that wasn't namespaced so nothing to worry about on that front.

@asharirfan I'll let you review on your own as well, and then we can decide on the versioning.

**Comment by asharirfan** [comment]
@tw2113 The PR looks good to me. I am thinking that we should also commit the vendor_prefixed directory to the repository. Because we will be shipping it with the plugin. What do you think?

**Comment by tw2113** [comment]
Yes we probably should

**Review by asharirfan — APPROVED** [review]

**Pull request merged**
